version: '2'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.frankfu.com.au'
    environment:
      VIRTUAL_HOST: gitlab.frankfu.com.au
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: gitlab.frankfu.com.au
      LETSENCRYPT_EMAIL: frankfu1122@gmail.com
      GITLAB_SHELL_SSH_PORT: 3000
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.frankfu.com.au'
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
        "X-Forwarded-Proto" => "https",
        "X-Forwarded-Ssl" => "on"
        }
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      # - '80:80'
      # - '443:443'
      - '2224:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

networks:
  default:
    external:
      name: nginx-proxy