version: '3'
services:
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
       - REDIS_HOSTS=mylabel:hostname:6379:0:password
    ports:
    - "8081:8081"