version: '2'

services:

  ghost:
    image: ghost:2-alpine
    restart: always
    ports: 
      - "2368:2368"
    environment:
      NODE_ENV: production
      # url: https://life.frankfu.com.au
      mail__transport: SMTP
      mail__options__service: Mailgun
      mail__options__auth__user: <My Mailgun User>
      mail__options__auth__pass: <My Mailgun Password>
      # VIRTUAL_HOST: life.frankfu.com.au
      # LETSENCRYPT_HOST: life.frankfu.com.au
      # LETSENCRYPT_EMAIL: frankfu1122@gmail.com
    volumes:
      - ~/data/ghost:/var/lib/ghost/content

networks:
  default:
    external:
      name: nginx-proxy
