version: '2'

services:
  web:
    user: "${UID}:${GID}"
    image: 'neo4j:3.5.7'
    restart: always
    hostname: 'neo4j.frankfu.com.au'
    environment:
      VIRTUAL_HOST: neo4j.frankfu.com.au
      VIRTUAL_PORT: 7474
      LETSENCRYPT_HOST: neo4j.frankfu.com.au
      LETSENCRYPT_EMAIL: frankfu1122@gmail.com
      NEO4J_AUTH: none
    volumes:
      - '~/data/neo4j/data:/data'      
      - '~/data/neo4j/logs:/logs'      
      - '~/data/neo4j/import:/var/lib/neo4j/import'      
      - '~/data/neo4j/plugins:/plugins'
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
networks:
  default:
    external:
      name: nginx-proxy