version: '3'

services:
  web:
    user: "${UID}:${GID}"
    image: 'neo4j:3.5.7'
    environment:
      NEO4J_AUTH: neo4j/test
    volumes:
      - '~/vlm/neo4j/data:/data'      
      - '~/vlm/neo4j/logs:/logs'      
      - '~/vlm/neo4j/import:/var/lib/neo4j/import'      
      - '~/vlm/neo4j/plugins:/plugins'
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"