version: '2'

services:
  web:
    image: 'jenkins/jenkins:lts'
    restart: always
    hostname: 'jenkins.frankfu.com.au'
    environment:
      VIRTUAL_HOST: jenkins.frankfu.com.au
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: jenkins.frankfu.com.au
      LETSENCRYPT_EMAIL: frankfu1122@gmail.com
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '~/data/jenkins_home:/var/jenkins_home'      
networks:
  default:
    external:
      name: nginx-proxy